import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/components/Provider";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { ToastProvider } from "./shop/_components/toast";
import CartModal from "@/components/CartList";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <ReduxProvider>
          <ToastProvider>
            <Header />
            <CartModal />
            {children}
            <Footer />
          </ToastProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
